name: Publish

on:
  release:
    types: [published]

jobs:
  modrinth:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6

      - name: Build
        shell: pwsh
        run: ./build.ps1 -Version "${{ github.event.release.tag_name }}"

      - name: Publish to Modrinth
        shell: pwsh
        env:
          MODRINTH_TOKEN: ${{ secrets.MODRINTH_TOKEN }}
          RELEASE_VERSION: ${{ github.event.release.tag_name }}
          RELEASE_CHANGELOG: ${{ github.event.release.body }}
        run: ./publish.ps1 -Version $env:RELEASE_VERSION -Changelog $env:RELEASE_CHANGELOG
